import Head from "next/head";
import { Container } from "@chakra-ui/react";
import Navbar from "../src/components/Navbar";
import Hero from "../src/components/Hero";
import Onboarding from "../src/components/Onboarding";
import Gallery from "../src/components/Gallery";
import ReadyTo from "../src/components/ReadyTo";
import Faq from "../src/components/Faq";
import Footer from "../src/components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lyne / Diseño gráfico a la medida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#ff5621"></meta>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#0099FE"></meta>
        <link rel="icon" href="/favicon.svg"/>
        <link rel="mask-icon" href="/mask-icon.svg" color="#1D1D1D"/>
        <link rel="apple-touch-icon" href="/apple-touch-icon.png"/>
        {/* <link rel="manifest" href="/manifest.json"/> */}
      </Head>

      <Container maxW={{ base: "90%", lg: "70%" }} p={0}>
        <Navbar/>
        <Hero/>
        <Onboarding/>
        <Gallery />
        <ReadyTo/>
        <Faq/>
        <Footer/>
      </Container>
    </div>
  );
}
